# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

import requests

# API endpoint
url = "https://api.imperva.com/v1/users"

# API key for authentication
headers = {
    "Authorization": "Bearer YOUR_API_KEY",
    "Content-Type": "application/json"
}

# User details
payload = {
    "name": "sudin,purushothaman@vodafone.com",
    "email": "sudin,purushothaman@vodafone.com",
    "role_id": "12345",  # Replace with the actual role ID
    "status": "active"
}

# Make the API call
response = requests.post(url, json=payload, headers=headers)

# Check the response
if response.status_code == 201:
    print("User created successfully:", response.json())
else:
    print("Failed to create user:", response.status_code, response.text)
